platform :ios, '12.0'

target 'Mutables' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Mutables
# Add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
    pod 'Firebase'


# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    
    pod 'GoogleSignIn'
     
    pod 'IQKeyboardManager'
    pod 'NVActivityIndicatorView'
    pod 'MagicTimer'

    pod 'lottie-ios'

end
